Marker Group:
  - Marker: 
    id: 0
    position:
    - [0]
    - [0]
    - [0]
    rotation:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  - Marker:
    id: 1
    position:
    - [0]
    - [0.61]
    - [0.285]
    rotation:
    - [1, 0, 0]
    - [0, 0, -1]
    - [0, 1, 0]
  
  - Marker:
    id: 2
    position:
    - [0]
    - [0.61]
    - [1.185]
    rotation:
    - [1, 0, 0]
    - [0, 0, -1]
    - [0, 1, 0]

  - Marker:
    id: 3
    position:
    - [0]
    - [0.61]
    - [2.085]
    rotation:
    - [1, 0, 0]
    - [0, 0, -1]
    - [0, 1, 0]

  - Marker:
    id: 4
    position:
    - [0]
    - [0.61]
    - [2.985]
    rotation:
    - [1, 0, 0]
    - [0, 0, -1]
    - [0, 1, 0]

  - Marker:
    id: 5
    position:
    - [0]
    - [0.265]
    - [4.12]
    rotation:
    - [1, 0, 0]
    - [0, -1, 0]
    - [0, 0, -1]

  - Marker:
    id: 6
    position:
    - [0]
    - [-0.635]
    - [4.12]
    rotation:
    - [1, 0, 0]
    - [0, -1, 0]
    - [0, 0, -1]

  - Marker:
    id: 7
    position:
    - [0]
    - [-1.535]
    - [4.12]
    rotation:
    - [1, 0, 0]
    - [0, -1, 0]
    - [0, 0, -1]

  - Marker:
    id: 8
    position:
    - [0]
    - [-2.435]
    - [4.12]
    rotation:
    - [1, 0, 0]
    - [0, -1, 0]
    - [0, 0, -1]

  - Marker:
    id: 16
    position:
    - [0]
    - [-2.7]
    - [0]
    rotation:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  - Marker:
    id: 17
    position:
    - [0]
    - [-1.8]
    - [0]
    rotation:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  - Marker:
    id: 18
    position:
    - [0]
    - [-0.9]
    - [0]
    rotation:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]